In [6]:
import pandas as pd
import polars as pl

In [7]:
data = pl.read_parquet("dataset/triplets-en/train-00000-of-00006.parquet")
data

shape: (10_000, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ query                          ┆ positive                       ┆ hard_negatives                 │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ binary                         ┆ list[binary]                   │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ What are the new               ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ anthropologic…                 ┆ …                              ┆ …                              │
│ What are the three main        ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ positi…                        ┆ …                              ┆ …                              │
│ Who are the three sisters      ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ know…                          ┆ …                              ┆ …                              │
│ What is the specific purpose   ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ o…                             ┆ …                              ┆ …                              │
│ How does the Yoast SEO Plugin  ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ …                              ┆ …                              ┆ …                              │
│ …                              ┆ …                              ┆ …                              │
│ What is the relationship       ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ betwe…                         ┆ …                              ┆ …                              │
│ What percentage of new         ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ infecti…                       ┆ …                              ┆ …                              │
│ What are the four scenarios    ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ fo…                            ┆ …                              ┆ …                              │
│ What are the visual            ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ difference…                    ┆ …                              ┆ …                              │
│ What are the two additional    ┆ b"\xff\xd8\xff\xe0\x00\x10JFIF ┆ [b"\xff\xd8\xff\xe0\x00\x10JFI │
│ co…                            ┆ …                              ┆ …                              │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

In [3]:
bench = pd.read_csv("results/vidore_colqwen3_5.csv")
bench

,subset,dims,n_queries,n_docs,ndcg@5,recall@1,recall@5,checkpoint
0,arxivqa,128,500.0,500.0,0.8176,0.7520,0.8720,final
1,arxivqa,256,500.0,500.0,0.8322,0.7800,0.8740,final
2,arxivqa,512,500.0,500.0,0.8418,0.7840,0.8920,final
3,arxivqa,1024,500.0,500.0,0.8462,0.7920,0.8920,final
4,docvqa,128,500.0,500.0,0.5421,0.4500,0.6220,final
5,docvqa,256,500.0,500.0,0.5588,0.4700,0.6380,final
6,docvqa,512,500.0,500.0,0.5640,0.4740,0.6420,final
7,docvqa,1024,500.0,500.0,0.5675,0.4820,0.6440,final
8,infovqa,128,500.0,500.0,0.8782,0.8240,0.9200,final
9,infovqa,256,500.0,500.0,0.8885,0.8440,0.9280,final
10,infovqa,512,500.0,500.0,0.8940,0.8500,0.9300,final
11,infovqa,1024,500.0,500.0,0.9034,0.8700,0.9320,final
12,shiftproject,128,100.0,1000.0,0.8617,0.7400,0.9700,final
13,shiftproject,256,100.0,1000.0,0.8875,0.7900,0.9600,final
14,shiftproject,512,100.0,1000.0,0.8881,0.7700,0.9800,final
15,shiftproject,1024,100.0,1000.0,0.9116,0.8200,0.9900,final
16,synth_ai,128,100.0,968.0,0.9906,0.9800,1.0000,final
17,synth_ai,256,100.0,968.0,0.9832,0.9600,1.0000,final
18,synth_ai,512,100.0,968.0,0.9832,0.9600,1.0000,final
19,synth_ai,1024,100.0,968.0,0.9869,0.9700,1.0000,final
20,synth_energy,128,100.0,977.0,0.9752,0.9500,0.9900,final
21,synth_energy,256,100.0,977.0,0.9702,0.9400,0.9900,final
22,synth_energy,512,100.0,977.0,0.9776,0.9600,0.9900,final
23,synth_energy,1024,100.0,977.0,0.9776,0.9600,0.9900,final
24,synth_gov,128,100.0,972.0,0.9598,0.9000,1.0000,final
25,synth_gov,256,100.0,972.0,0.9602,0.9200,0.9900,final
26,synth_gov,512,100.0,972.0,0.9530,0.9000,0.9900,final
27,synth_gov,1024,100.0,972.0,0.9529,0.9100,0.9800,final
28,synth_health,128,100.0,965.0,0.9776,0.9600,0.9900,final
29,synth_health,256,100.0,965.0,0.9863,0.9800,0.9900,final
30,synth_health,512,100.0,965.0,0.9863,0.9800,0.9900,final
31,synth_health,1024,100.0,965.0,0.9826,0.9700,0.9900,final
32,tabfquad,128,280.0,70.0,0.8441,0.7857,0.8857,final
33,tabfquad,256,280.0,70.0,0.8739,0.8214,0.9179,final
34,tabfquad,512,280.0,70.0,0.8978,0.8357,0.9500,final
35,tabfquad,1024,280.0,70.0,0.9078,0.8500,0.9607,final
36,tatdqa,128,1663.0,277.0,0.7595,0.6464,0.8545,final
37,tatdqa,256,1663.0,277.0,0.7788,0.6699,0.8683,final
38,tatdqa,512,1663.0,277.0,0.7801,0.6735,0.8683,final
39,tatdqa,1024,1663.0,277.0,0.7857,0.6819,0.8743,final
40,biomedical_v2,128,640.0,1016.0,0.5533,0.3264,0.5809,final
41,biomedical_v2,256,640.0,1016.0,0.5789,0.3514,0.6030,final
42,biomedical_v2,512,640.0,1016.0,0.5783,0.3510,0.5976,final
43,biomedical_v2,1024,640.0,1016.0,0.5737,0.3419,0.5969,final
44,economics_v2,128,232.0,452.0,0.5685,0.1099,0.3016,final
45,economics_v2,256,232.0,452.0,0.5628,0.1294,0.3059,final
46,economics_v2,512,232.0,452.0,0.5422,0.1138,0.2950,final
47,economics_v2,1024,232.0,452.0,0.5161,0.1035,0.2887,final
48,esg_human_v2,128,104.0,3076.0,0.3431,0.1314,0.4412,final
49,esg_human_v2,256,104.0,3076.0,0.3870,0.1577,0.4960,final
50,esg_human_v2,512,104.0,3076.0,0.4372,0.2513,0.5391,final
51,esg_human_v2,1024,104.0,3076.0,0.4375,0.2628,0.5337,final
52,esg_v2,128,228.0,1538.0,0.4927,0.2368,0.5404,final
53,esg_v2,256,228.0,1538.0,0.5225,0.2827,0.5540,final
54,esg_v2,512,228.0,1538.0,0.5162,0.2682,0.5412,final
55,esg_v2,1024,228.0,1538.0,0.5178,0.2779,0.5468,final
56,AVERAGE,128,NaN,NaN,0.7546,0.6280,0.7835,final
57,AVERAGE,256,NaN,NaN,0.7693,0.6497,0.7939,final
58,AVERAGE,512,NaN,NaN,0.7743,0.6551,0.8004,final
59,AVERAGE,1024,NaN,NaN,0.7762,0.6637,0.8014,final